=== mmussett/LIB_UTIL_CSF/LIB_UTIL_CSF-implement.module/Schemas/Internal/UTIL/CSF/ResourceUrl_v1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:url="http://www.royallondon.com/xsd/internal/util/csf/resouceurl/v1" elementFormDefault="qualified" targetNamespace="http://www.royallondon.com/xsd/internal/util/csf/resouceurl/v1">

    <element name="ABE2" type="url:ABEType"/>
    <element name="ABE3" type="url:ABEType"/>
    <element name="ResourceName" type="url:ABEType"/>
    <element name="Pattern" type="string"/>

    <element name="IdCount">
    	<simpleType>
    		<restriction base="short">
    			<minInclusive value="0"/>
    			<maxInclusive value="3"/>
    		</restriction>
    	</simpleType>
    </element>
    <element name="URL" type="string"/>

    <simpleType name="ABEType">
    	<restriction base="string"/>
    </simpleType>

    <complexType name="ResourceURLType">
    	<sequence>
    		<sequence minOccurs="0">
    			<element ref="url:ABE2" />
    			<element minOccurs="0" ref="url:ABE3" />
    		</sequence>
    		<element ref="url:ResourceName" />
    		<element ref="url:Version"/>
    		<element ref="url:IdCount" />
    		<element ref="url:URL" />
    	</sequence>
    </complexType>

    <complexType name="ResourceURLInfoListType">
    	<sequence>
    		<element maxOccurs="unbounded" minOccurs="1" ref="url:ResourceURLInfo"/>
    	</sequence>
    </complexType>

    <complexType name="ResourceURLInfoType">
    	<sequence>
    		<sequence minOccurs="0">
    			<element ref="url:ABE2" />
    			<element minOccurs="0" ref="url:ABE3" />
    		</sequence>
    		<element ref="url:ResourceName" />
    		<element ref="url:Version"/>
    	</sequence>
    </complexType>

    <complexType name="ResourceURLListType">
    	<sequence>
    		<element maxOccurs="unbounded" minOccurs="1" ref="url:ResourceURL"/>
    	</sequence>
    </complexType>

    <complexType name="RegExpResourceType">
    	<sequence>
    		<element ref="url:Pattern" />
    		<element ref="url:URL" />
    		<element ref="url:Ids" />
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    </complexType>

    <complexType name="RegExpResourceListType">
    	<sequence>
    		<element maxOccurs="unbounded" minOccurs="1" ref="url:RegExpResource"/>
    	</sequence>
    </complexType>

    <element name="ResourceURLInfoList" type="url:ResourceURLInfoListType"/>
    <element name="ResourceURLInfo" type="url:ResourceURLInfoType"/>

    <element name="ResourceURLList" type="url:ResourceURLListType"/>
    <element name="ResourceURL" type="url:ResourceURLType"/>

    <element name="RegExpResourceList" type="url:RegExpResourceListType"/>
    <element name="RegExpResource" type="url:RegExpResourceType"/>

    <element name="Ids" type="string"></element>

    <element name="Version" type="short"></element>
</schema>

=== mmussett/LIB_UTIL_CSF/LIB_UTIL_CSF-implement.module/Resources/util/csf_v1/xml/ResourceUrl.xml
<?xml version="1.0" encoding="UTF-8"?>
<ResourceURLList xmlns="http://www.royallondon.com/xsd/internal/util/csf/resouceurl/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.royallondon.com/xsd/internal/util/csf/resouceurl/v1 ../../../../Schemas/Internal/UTIL/CSF/ResourceUrl_v1.xsd ">
  <ResourceURL>
    <ResourceName>advisors</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/advisors</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>agreements</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/agreements</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/customers</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id-beneficiaries</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2/beneficiaries</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id-charges</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2/charges</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id-charges-history</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2/charges/history</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id-contributions</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2/contributions</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id-contributions-history</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2/contributions/history</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id-investment</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2/investment</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id-investment-history</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2/investment/history</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>customers-id-legal</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/customers/$2/legal</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>documents</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/documents</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>documents-id</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/documents/$2</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>events</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/events</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>exits-id-cashInQuotes</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/exits/$2/cashInQuotes</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>exits-id-quotes</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/exits/$2/quotes</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>funds</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/funds</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>investments</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/investments</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>investments-id-investmentChoices</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/investments/$2/investmentChoices</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>panelClients</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/panelClients</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>policies</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/policies</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>policies-id</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/policies/$2</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>policies-id-beneficiaries</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/policies/$2/beneficiaries</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>policies-id-beneficiaries-id</ResourceName>
    <Version>1</Version>
    <IdCount>2</IdCount>
    <URL>/policies/$2/beneficiaries/$3</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>policies-id-contributors</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/policies/$2/contributors</URL>
  </ResourceURL>
  <ResourceURL>
    <ResourceName>policies-id-contributors-id</ResourceName>
    <Version>1</Version>
    <IdCount>2</IdCount>
    <URL>/policies/$2/contributors/$3</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>applicants</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/sales/v$1/applicants</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>applicants-id</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/applicants/$2</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>applicants-id-contacts</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/applicants/$2/contacts</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>applicants-id-contacts-id</ResourceName>
    <Version>1</Version>
    <IdCount>2</IdCount>
    <URL>/sales/v$1/applicants/$2/contacts/$3</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>applications</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/sales/v$1/applications</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>applications-id-submit</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/applications/$2/submit</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>applications-id-validate</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/applications/$2/validate</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>applications-id</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/applications/$2</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>illustrations</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/sales/v$1/illustrations</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>illustrations-id</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/illustrations/$2</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>illustrations-attachments</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/sales/v$1/illustrations/attachments</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>illustrations-attachments-id</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/illustrations/attachments/$2</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals</ResourceName>
    <Version>1</Version>
    <IdCount>0</IdCount>
    <URL>/sales/v$1/proposals</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/proposals/$2</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-beneficiaries</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/proposals/$2/beneficiaries</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-beneficiaries-id</ResourceName>
    <Version>1</Version>
    <IdCount>2</IdCount>
    <URL>/sales/v$1/proposals/$2/beneficiaries/$3</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-charges</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/proposals/$2/charges</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-charges-id</ResourceName>
    <Version>1</Version>
    <IdCount>2</IdCount>
    <URL>/sales/v$1/proposals/$2/charges/$3</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-increments</ResourceName>
    <Version>1</Version>
    <IdCount>1</IdCount>
    <URL>/sales/v$1/proposals/$2/increments</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-increments-id</ResourceName>
    <Version>1</Version>
    <IdCount>2</IdCount>
    <URL>/sales/v$1/proposals/$2/increments/$3</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-increments-id-contributions</ResourceName>
    <Version>1</Version>
    <IdCount>2</IdCount>
    <URL>/sales/v$1/proposals/$2/increments/$3/contributions</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-increments-id-contributions-id</ResourceName>
    <Version>1</Version>
    <IdCount>3</IdCount>
    <URL>/sales/v$1/proposals/$2/increments/$3/contributions/$4</URL>
  </ResourceURL>
  <ResourceURL>
    <ABE2>sales</ABE2>
    <ResourceName>proposals-id-increments-id-transferIns</ResourceName>
